2020-11-29 21:35:39,908	INFO services.py:1104 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
wandb: ERROR Attempted to change value of key "train_batch_size" from 49666 to 89600
wandb: ERROR If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "train_wandb_impala.py", line 202, in <module>
    train_func()
  File "train_wandb_impala.py", line 167, in train_func
    config['train_batch_size'] = config['num_workers'] * config['num_envs_per_worker'] * config['rollout_fragment_length']
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 130, in __setitem__
    key, val = self._sanitize(key, val)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 212, in _sanitize
    raise config_util.ConfigError(
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "train_batch_size" from 49666 to 89600
If you really want to do this, pass allow_val_change=True to config.update()
