{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "I have detected 80 CPUs here, so I'm going to create 79 actors\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import multiprocessing as mp\n",
    "import plotly.io as pio\n",
    "import ray\n",
    "from ray import tune\n",
    "\n",
    "from JSS.CustomCallbacks import CustomCallbacks\n",
    "from JSS.env.JSS import JSS\n",
    "from ray.rllib.agents.ppo import ppo, PPOTrainer\n",
    "\n",
    "from ray.tune.logger import DEFAULT_LOGGERS\n",
    "from ray.tune.integration.wandb import WandbLogger\n",
    "\n",
    "from JSS.env_wrapper import BestActionsWrapper\n",
    "\n",
    "from JSS.models import FCMaskedActionsModel\n",
    "\n",
    "pio.orca.config.use_xvfb = True\n",
    "import wandb\n",
    "\n",
    "'''\n",
    "            'lr': {\n",
    "                'values': [5e-5, 1e-5]\n",
    "            },\n",
    "            'lambda': {\n",
    "                'values': [0.90, 0.95, 1.0]\n",
    "            },\n",
    "            'clip_param': {\n",
    "                'values': [0.2, 0.3, 0.4]\n",
    "            },\n",
    "            'num_sgd_iter': {\n",
    "                'values': [30, 35, 40]\n",
    "            },\n",
    "            'entropy_coeff': {\n",
    "                'values': [0.0, 1e-4]\n",
    "            }\n",
    "'''\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"I have detected {} CPUs here, so I'm going to create {} actors\".format(mp.cpu_count(), mp.cpu_count() - 1))\n",
    "    os.environ[\"WANDB_API_KEY\"] = '3487a01956bf67cc7882bca2a38f70c8c95f8463'\n",
    "    sweep_config = {\n",
    "        'program': 'random_loop.py',\n",
    "        'method': 'grid',\n",
    "        'metric': {\n",
    "            'name': 'time_step_min',\n",
    "            'goal': 'minimize',\n",
    "        },\n",
    "        'parameters': {\n",
    "            'instance_path': {\n",
    "                'values': ['/JSS/JSS/env/instances/ta51', '/JSS/JSS/env/instances/ta52', '/JSS/JSS/env/instances/ta53', '/JSS/JSS/env/instances/ta54',\n",
    "                           '/JSS/JSS/env/instances/ta55', '/JSS/JSS/env/instances/ta56', '/JSS/JSS/env/instances/ta57', '/JSS/JSS/env/instances/ta58',\n",
    "                           '/JSS/JSS/env/instances/ta59', '/JSS/JSS/env/instances/ta60']\n",
    "            }\n",
    "        }\n",
    "    }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Create sweep with ID: 4kvs4n7l\n",
      "Sweep URL: https://wandb.ai/ingambe/RLLIB_SWEEP_2/sweeps/4kvs4n7l\n"
     ]
    }
   ],
   "source": [
    "sweep_id = wandb.sweep(sweep_config, project=\"RLLIB_SWEEP_2\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[34m\u001b[1mwandb\u001b[0m: Starting wandb agent üïµÔ∏è\n",
      "2020-10-13 10:31:26,613 - wandb.wandb_agent - INFO - Running runs: []\n",
      "2020-10-13 10:31:30,470 - wandb.wandb_agent - INFO - Agent received command: run\n",
      "2020-10-13 10:31:30,470 - wandb.wandb_agent - INFO - Agent starting run with config:\n",
      "\tinstance_path: /JSS/JSS/env/instances/ta51\n",
      "2020-10-13 10:31:30,471 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python random.py --instance_path=/JSS/JSS/env/instances/ta51\n",
      "Traceback (most recent call last):\n",
      "  File \"bit_generator.pyx\", line 40, in numpy.random.bit_generator\n",
      "  File \"/root/miniconda3/lib/python3.8/secrets.py\", line 20, in <module>\n",
      "    from random import SystemRandom\n",
      "  File \"/JSS/JSS/random.py\", line 2, in <module>\n",
      "    import wandb\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/__init__.py\", line 37, in <module>\n",
      "    from wandb import sdk as wandb_sdk\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/__init__.py\", line 8, in <module>\n",
      "    from .wandb_artifacts import Artifact  # noqa: F401\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py\", line 6, in <module>\n",
      "    import requests\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/requests/__init__.py\", line 112, in <module>\n",
      "    from . import utils\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/requests/utils.py\", line 19, in <module>\n",
      "    import tempfile\n",
      "  File \"/root/miniconda3/lib/python3.8/tempfile.py\", line 45, in <module>\n",
      "    from random import Random as _Random\n",
      "ImportError: cannot import name 'Random' from partially initialized module 'random' (most likely due to a circular import) (/JSS/JSS/random.py)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"random.py\", line 1, in <module>\n",
      "    import ray\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/ray/__init__.py\", line 56, in <module>\n",
      "    import ray._raylet  # noqa: E402\n",
      "  File \"python/ray/_raylet.pyx\", line 10, in init ray._raylet\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/numpy/__init__.py\", line 151, in <module>\n",
      "    from . import random\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/numpy/random/__init__.py\", line 179, in <module>\n",
      "    from . import _pickle\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/numpy/random/_pickle.py\", line 1, in <module>\n",
      "    from .mtrand import RandomState\n",
      "  File \"mtrand.pyx\", line 1, in init numpy.random.mtrand\n",
      "  File \"bit_generator.pyx\", line 43, in init numpy.random.bit_generator\n",
      "  File \"/JSS/JSS/random.py\", line 2, in <module>\n",
      "    import wandb\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/__init__.py\", line 37, in <module>\n",
      "    from wandb import sdk as wandb_sdk\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/__init__.py\", line 8, in <module>\n",
      "    from .wandb_artifacts import Artifact  # noqa: F401\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py\", line 6, in <module>\n",
      "    import requests\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/requests/__init__.py\", line 112, in <module>\n",
      "    from . import utils\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/requests/utils.py\", line 19, in <module>\n",
      "    import tempfile\n",
      "  File \"/root/miniconda3/lib/python3.8/tempfile.py\", line 45, in <module>\n",
      "    from random import Random as _Random\n",
      "ImportError: cannot import name 'Random' from partially initialized module 'random' (most likely due to a circular import) (/JSS/JSS/random.py)\n",
      "2020-10-13 10:31:35,489 - wandb.wandb_agent - INFO - Running runs: ['f2gizgn5']\n",
      "2020-10-13 10:31:35,490 - wandb.wandb_agent - INFO - Cleaning up finished run: f2gizgn5\n",
      "2020-10-13 10:31:35,832 - wandb.wandb_agent - INFO - Agent received command: run\n",
      "2020-10-13 10:31:35,833 - wandb.wandb_agent - INFO - Agent starting run with config:\n",
      "\tinstance_path: /JSS/JSS/env/instances/ta52\n",
      "2020-10-13 10:31:35,835 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python random.py --instance_path=/JSS/JSS/env/instances/ta52\n",
      "Traceback (most recent call last):\n",
      "  File \"bit_generator.pyx\", line 40, in numpy.random.bit_generator\n",
      "  File \"/root/miniconda3/lib/python3.8/secrets.py\", line 20, in <module>\n",
      "    from random import SystemRandom\n",
      "  File \"/JSS/JSS/random.py\", line 2, in <module>\n",
      "    import wandb\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/__init__.py\", line 37, in <module>\n",
      "    from wandb import sdk as wandb_sdk\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/__init__.py\", line 8, in <module>\n",
      "    from .wandb_artifacts import Artifact  # noqa: F401\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py\", line 6, in <module>\n",
      "    import requests\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/requests/__init__.py\", line 112, in <module>\n",
      "    from . import utils\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/requests/utils.py\", line 19, in <module>\n",
      "    import tempfile\n",
      "  File \"/root/miniconda3/lib/python3.8/tempfile.py\", line 45, in <module>\n",
      "    from random import Random as _Random\n",
      "ImportError: cannot import name 'Random' from partially initialized module 'random' (most likely due to a circular import) (/JSS/JSS/random.py)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"random.py\", line 1, in <module>\n",
      "    import ray\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/ray/__init__.py\", line 56, in <module>\n",
      "    import ray._raylet  # noqa: E402\n",
      "  File \"python/ray/_raylet.pyx\", line 10, in init ray._raylet\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/numpy/__init__.py\", line 151, in <module>\n",
      "    from . import random\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/numpy/random/__init__.py\", line 179, in <module>\n",
      "    from . import _pickle\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/numpy/random/_pickle.py\", line 1, in <module>\n",
      "    from .mtrand import RandomState\n",
      "  File \"mtrand.pyx\", line 1, in init numpy.random.mtrand\n",
      "  File \"bit_generator.pyx\", line 43, in init numpy.random.bit_generator\n",
      "  File \"/JSS/JSS/random.py\", line 2, in <module>\n",
      "    import wandb\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/__init__.py\", line 37, in <module>\n",
      "    from wandb import sdk as wandb_sdk\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/__init__.py\", line 8, in <module>\n",
      "    from .wandb_artifacts import Artifact  # noqa: F401\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py\", line 6, in <module>\n",
      "    import requests\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/requests/__init__.py\", line 112, in <module>\n",
      "    from . import utils\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/requests/utils.py\", line 19, in <module>\n",
      "    import tempfile\n",
      "  File \"/root/miniconda3/lib/python3.8/tempfile.py\", line 45, in <module>\n",
      "    from random import Random as _Random\n",
      "ImportError: cannot import name 'Random' from partially initialized module 'random' (most likely due to a circular import) (/JSS/JSS/random.py)\n",
      "2020-10-13 10:31:40,853 - wandb.wandb_agent - INFO - Running runs: ['hb8zrj3k']\n",
      "2020-10-13 10:31:40,854 - wandb.wandb_agent - INFO - Cleaning up finished run: hb8zrj3k\n",
      "2020-10-13 10:31:41,206 - wandb.wandb_agent - INFO - Agent received command: run\n",
      "2020-10-13 10:31:41,207 - wandb.wandb_agent - INFO - Agent starting run with config:\n",
      "\tinstance_path: /JSS/JSS/env/instances/ta53\n",
      "2020-10-13 10:31:41,209 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python random.py --instance_path=/JSS/JSS/env/instances/ta53\n",
      "Traceback (most recent call last):\n",
      "  File \"bit_generator.pyx\", line 40, in numpy.random.bit_generator\n",
      "  File \"/root/miniconda3/lib/python3.8/secrets.py\", line 20, in <module>\n",
      "    from random import SystemRandom\n",
      "  File \"/JSS/JSS/random.py\", line 2, in <module>\n",
      "    import wandb\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/__init__.py\", line 37, in <module>\n",
      "    from wandb import sdk as wandb_sdk\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/__init__.py\", line 8, in <module>\n",
      "    from .wandb_artifacts import Artifact  # noqa: F401\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py\", line 6, in <module>\n",
      "    import requests\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/requests/__init__.py\", line 112, in <module>\n",
      "    from . import utils\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/requests/utils.py\", line 19, in <module>\n",
      "    import tempfile\n",
      "  File \"/root/miniconda3/lib/python3.8/tempfile.py\", line 45, in <module>\n",
      "    from random import Random as _Random\n",
      "ImportError: cannot import name 'Random' from partially initialized module 'random' (most likely due to a circular import) (/JSS/JSS/random.py)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"random.py\", line 1, in <module>\n",
      "    import ray\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/ray/__init__.py\", line 56, in <module>\n",
      "    import ray._raylet  # noqa: E402\n",
      "  File \"python/ray/_raylet.pyx\", line 10, in init ray._raylet\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/numpy/__init__.py\", line 151, in <module>\n",
      "    from . import random\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/numpy/random/__init__.py\", line 179, in <module>\n",
      "    from . import _pickle\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/numpy/random/_pickle.py\", line 1, in <module>\n",
      "    from .mtrand import RandomState\n",
      "  File \"mtrand.pyx\", line 1, in init numpy.random.mtrand\n",
      "  File \"bit_generator.pyx\", line 43, in init numpy.random.bit_generator\n",
      "  File \"/JSS/JSS/random.py\", line 2, in <module>\n",
      "    import wandb\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/__init__.py\", line 37, in <module>\n",
      "    from wandb import sdk as wandb_sdk\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/__init__.py\", line 8, in <module>\n",
      "    from .wandb_artifacts import Artifact  # noqa: F401\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py\", line 6, in <module>\n",
      "    import requests\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/requests/__init__.py\", line 112, in <module>\n",
      "    from . import utils\n",
      "  File \"/root/miniconda3/lib/python3.8/site-packages/requests/utils.py\", line 19, in <module>\n",
      "    import tempfile\n",
      "  File \"/root/miniconda3/lib/python3.8/tempfile.py\", line 45, in <module>\n",
      "    from random import Random as _Random\n",
      "ImportError: cannot import name 'Random' from partially initialized module 'random' (most likely due to a circular import) (/JSS/JSS/random.py)\n",
      "2020-10-13 10:31:46,226 - wandb.wandb_agent - INFO - Running runs: ['ey28b8v6']\n",
      "2020-10-13 10:31:46,227 - wandb.wandb_agent - ERROR - Detected 3 failed runs in the first 60 seconds, shutting down.\n",
      "2020-10-13 10:31:46,227 - wandb.wandb_agent - INFO - To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Terminating and syncing runs. Press ctrl-c to kill.\n"
     ]
    }
   ],
   "source": [
    "!wandb agent 4kvs4n7l"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
